theme: minima
title: Tech Entrepreneur / Lawyer / Learner
author: Richard Ruth
email: richard@rnvsg.com
description: > # this means to ignore newlines until "baseurl:"
  This site highlights information about tech entrepreneur and lawyer Richard Ruth and his career coding journey and projects.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
